GAMEPAD_ACTION_DOWN  cycle pause
GAMEPAD_ACTION_RIGHT cycle pause

GAMEPAD_DPAD_RIGHT   playlist-next
GAMEPAD_DPAD_LEFT    playlist-prev
GAMEPAD_DPAD_UP      seek +10
GAMEPAD_DPAD_DOWN    seek -10

GAMEPAD_BACK_LEFT    playlist-prev
GAMEPAD_BACK_RIGHT   playlist-next

GAMEPAD_ACTION_LEFT  show-text "${playlist-pos-1}/${playlist-count}: ${media-title}" 5000
GAMEPAD_ACTION_UP    cycle shuffle

GAMEPAD_BACK         show-progress
GAMEPAD_START        quit
